
import AbstractEntity from "idb-entity/es2015/AbstractEntity"
import SubscriptionState from "./SubscriptionState"
import SubscriptionType from "./SubscriptionType"
import objectStore from "../decorator/objectStore"

@objectStore("Subscription")
export default class Subscription extends AbstractEntity {
  /**
   * Internal ID of this subscription record generated by the Indexed DB object
   * store.
   */
  id: number;

  /**
   * The type of this subscription, must be one of the
   * {@linkcode SubscriptionType.*} constants.
   */
  type: string;

  /**
   * The ID of the playlist from which the videos should be retrieved. This
   * is the "uploads" playlist if this is a subscription to a YouTube
   * channel.
   */
  playlistId: string;

  /**
   * The ID of the channel to which the subscription is made to. The field is
   * the ID of the channel owning the playlist for incognito subscriptions to
   * playlist.
   */
  channelId: string;

  /**
   * The state of this subscription, must be one of the
   * {@linkcode SubscriptionState.*} constants.
   */
  state: string;

  /**
   * The last reported error related to this subscription, set to {@code null}
   * if there is no current error.
   */
  lastError: ?string;

  /**
   * The ID of the Google account from which this subscription has been
   * provided. The field is {@code null} if this is an incognito subscription.
   */
  accountId: string;

  /**
   * Set to {@code 1} if this is an incognito subscription (has been provided
   * manually instead of read from YouTube channel subscriptions); set to
   * {@code 0} otherwise.
   */
  isIncognito: number;
}
